name: "Version Branch Generator"
description: "Generates the version based on the branch name"
inputs:
  type:
    description: Can be 'lib' or 'dotnet-app' or 'fe-app'
    required: true
  package-version:
    description: "Package version"
    required: true
outputs:
  app-version:
    description: "Generated app version"
runs:
  using: "node20"
  main: "dist/index.js"
