name: "Odin Version Builder"
description: "Generates the version based on the branch name"

inputs:
  type:
    description: Can be 'lib' or 'dotnet-app' or 'fe-app'
    required: true
  package-version:
    description: "Package version"
    required: true

outputs:
  version:
    description: "Build version generated e.g. '1.5.6-dev.123'."
  major-version:
    description: "Returns the major version e.g. '1'"
  minor-version:
    description: "Returns the minor version e.g. '5'"
  patch-version:
    description: "Returns the patch version e.g. '6'"

runs:
  using: "node20"
  main: "dist/index.js"
