name: "Version Branch Generator"
description: "Generates the version based on the branch name"
inputs:
  type:
    description: Can be 'lib' or 'deploy'
    required: true
  package-version:
    description: "Package version"
    required: true
outputs:
  app-version:
    description: "The app version generated"
runs:
  using: "node20"
  main: "index.js"
