name: "Sync Main Release"
description: "Syncs the release branch with the latest changes from the main branch"
inputs:
  release-branch:
    description: "The release branch that needs to be synced with main"
    required: true
outputs:
  app-version:
    description: "The app version generated"
runs:
  using: "node20"
  main: "dist/index.js"
