name: "Lock Branch"

description: "Lock a branch by setting its protection rules after code review approval."

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  branch_name:
    description: "The name of the branch to lock"
    required: true
  require_code_owner_reviews:
    description: "Require Code Owner approval"
    required: false
    default: true
  required_approval_count:
    description: "The number of approvals required"
    required: false
    default: 1
  required_status_checks:
    description: "Array of required status checks"
    required: false
    default: "[]"
  strict_status_check:
    description: "Require status checks to be up-to-date before merging"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Lock Branch
      shell: bash
      run: |
        echo "Locking branch: ${{ inputs.branch_name }}"

        REQUIRE_CODE_OWNERS=${{ inputs.require_code_owner_reviews }}
        REQUIRED_APPROVAL_COUNT=${{ inputs.required_approval_count }}
        REQUIRED_STATUS_CHECKS=${{ inputs.required_status_checks }}
        STRICT_STATUS_CHECK=${{ inputs.strict_status_check }}

        if [ "$REQUIRED_STATUS_CHECKS" != "[]" ] && [ -n "$REQUIRED_STATUS_CHECKS" ]; then
          echo "Required status checks: $REQUIRED_STATUS_CHECKS"
          echo "Strict status check: $STRICT_STATUS_CHECK"
          STATUS_CHECKS="{\"strict\": $STRICT_STATUS_CHECK, \"contexts\": $REQUIRED_STATUS_CHECKS}"
        else
          echo "No status checks required"
          STATUS_CHECKS='null'
        fi

        echo "Locking branch with $REQUIRED_APPROVAL_COUNT required approvals, code owner review requirement set to $REQUIRE_CODE_OWNERS and status checks $STATUS_CHECKS"

        gh api -X PUT "/repos/${{ github.repository }}/branches/${{ inputs.branch_name }}/protection" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ inputs.github_token }}" \
          --input - <<EOF
        {
          "required_pull_request_reviews": {
            "dismiss_stale_reviews": false,
            "require_code_owner_reviews": ${REQUIRE_CODE_OWNERS},
            "required_approving_review_count": ${REQUIRED_APPROVAL_COUNT}
          },
          "required_status_checks": ${STATUS_CHECKS},
          "restrictions": null,
          "enforce_admins": false,
          "allow_deletions": true
        }
        EOF

      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
