name: "Sync Jira Releases"
description: "Syncs the release with Jira, creating a new release in the specified Jira project"
inputs:
  jira-url:
    description: "The URL of the Jira instance"
    required: false
    default: "https://rivertechnologies.atlassian.net"
runs:
  using: "node20"
  main: "dist/index.js"
